import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import '../utils/constants.dart';

/// A column of social media buttons and a divider, aligned to the bottom of a
/// screen. The column takes up one unit of space in its parent [Row].
///
/// The buttons are generated by [socialButtons], and the divider is a
/// [VerticalDivider] that is 150 logical pixels tall and 2 logical pixels wide.
Expanded socialWidget() {
  return Expanded(
    flex: 1,
    child: Column(
      mainAxisAlignment: MainAxisAlignment.end,
      children: [
        ...socialButtons(),
        const SizedBox(
          height: 150,
          child: VerticalDivider(
            width: 2,
          ),
        )
      ],
    ),
  );
}

  /// Creates a custom [IconButton] with the given [iconData] and [onPressed]
  /// callback. The button is colored with [Colors.teal.shade100] and is
  /// otherwise unstyled.
Widget customIconButton(
    {required IconData iconData, required VoidCallback onPressed}) {
  return IconButton(
      icon: FaIcon(
        iconData,
        color: Colors.teal.shade100,
      ),
      onPressed: onPressed);
}

  /// Returns a list of custom [IconButton]s for linking to social media and
  /// contact platforms.
  ///
  /// The [IconButton]s are for LinkedIn, GitHub, WhatsApp, and email. The
  /// respective link URLs are:
  ///
  /// * LinkedIn: https://www.linkedin.com/in/nivethan30/
  /// * GitHub: https://github.com/nivethan30
  /// * WhatsApp: https://api.whatsapp.com/send/?phone=%2B918220475560&text=Hey%20there!&type=phone_number&app_absent=0
  /// * Email: uses the [launchMail] function to open the default email client
  ///   and compose a new email
List<Widget> socialButtons() {
  return [
    customIconButton(
        iconData: FontAwesomeIcons.linkedin,
        onPressed: () {
          launchURL('https://www.linkedin.com/in/nivethan30/');
        }),
    customIconButton(
        iconData: FontAwesomeIcons.github,
        onPressed: () {
          launchURL("https://github.com/nivethan30");
        }),
    customIconButton(
        iconData: FontAwesomeIcons.whatsapp,
        onPressed: () {
          launchURL(
              'https://api.whatsapp.com/send/?phone=%2B918220475560&text=Hey%20there!&type=phone_number&app_absent=0');
        }),
    customIconButton(
        iconData: FontAwesomeIcons.envelope,
        onPressed: () {
          launchMail();
        }),
  ];
}
